definitions:
  helper.ResponseError:
    properties:
      error:
        type: string
    type: object
  helper.ResponseSuccess:
    properties:
      data: {}
    type: object
  model.AuthResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/model.UserDTO'
    type: object
  model.ChangeEmailRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
  model.ChangePasswordRequest:
    properties:
      confirm_password:
        type: string
      new_password:
        maxLength: 72
        minLength: 8
        type: string
      old_password:
        type: string
    required:
    - confirm_password
    - new_password
    type: object
  model.GoogleLoginRequest:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  model.LoginRequest:
    properties:
      captcha_token:
        type: string
      email:
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - captcha_token
    - email
    - password
    type: object
  model.RegisterUserRequest:
    properties:
      captcha_token:
        type: string
      code:
        type: string
      email:
        type: string
      full_name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - captcha_token
    - code
    - email
    - full_name
    - password
    type: object
  model.ResetPasswordRequest:
    properties:
      captcha_token:
        type: string
      code:
        type: string
      confirm_password:
        type: string
      email:
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - captcha_token
    - code
    - confirm_password
    - email
    - password
    type: object
  model.SendOTPRequest:
    properties:
      captcha_token:
        type: string
      email:
        type: string
      mode:
        type: string
    required:
    - captcha_token
    - email
    - mode
    type: object
  model.UserDTO:
    properties:
      avatar:
        type: string
      bio:
        type: string
      email:
        type: string
      full_name:
        type: string
      has_password:
        type: boolean
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/account/email:
    put:
      consumes:
      - application/json
      description: Change user email. Requires OTP verification.
      parameters:
      - description: Change Email Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ChangeEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      security:
      - BearerAuth: []
      summary: Change Email
      tags:
      - account
  /api/account/password:
    put:
      consumes:
      - application/json
      description: Change user password. Requires old password if one is set.
      parameters:
      - description: Change Password Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      security:
      - BearerAuth: []
      summary: Change Password
      tags:
      - account
  /api/auth/google:
    post:
      consumes:
      - application/json
      description: Exchange Google ID Token for App Token and User Info
      parameters:
      - description: Google Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.GoogleLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/model.AuthResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      summary: Google Exchange
      tags:
      - auth
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/model.AuthResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      summary: Login
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with email, password, and OTP verification.
      parameters:
      - description: Register User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/model.AuthResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      summary: Register User
      tags:
      - auth
  /api/auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset user password using OTP verification.
      parameters:
      - description: Reset Password Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      summary: Reset Password
      tags:
      - auth
  /api/otp/send:
    post:
      consumes:
      - application/json
      description: Sends an OTP code to the user's email for registration or password
        reset.
      parameters:
      - description: Send OTP Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      summary: Send OTP
      tags:
      - otp
  /api/user/current:
    get:
      consumes:
      - application/json
      description: Get the currently logged-in user's profile.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/model.UserDTO'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      security:
      - BearerAuth: []
      summary: Get Current User
      tags:
      - user
  /api/user/profile:
    put:
      consumes:
      - multipart/form-data
      description: Update user's full name, bio, and avatar.
      parameters:
      - description: Full Name
        in: formData
        name: full_name
        required: true
        type: string
      - description: Bio
        in: formData
        name: bio
        type: string
      - description: Avatar Image
        in: formData
        name: avatar
        type: file
      - description: Delete Avatar
        in: formData
        name: delete_avatar
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/model.UserDTO'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.ResponseError'
      security:
      - BearerAuth: []
      summary: Update User Profile
      tags:
      - user
swagger: "2.0"
